{{ config(schema='STAGING_ONS', materialized='view') }}

WITH raw_data AS (
  SELECT * FROM {{ source('raw_ons', 'INMET_PROCESSED_DATA_2023') }}
  UNION ALL
  SELECT * FROM {{ source('raw_ons', 'INMET_PROCESSED_DATA_2024') }}
  UNION ALL
  SELECT * FROM {{ source('raw_ons', 'INMET_PROCESSED_DATA_2025') }}
)

SELECT
  REGIAO,
  UF,
  ESTACAO,
  TRY_TO_DATE(DATA, 'YYYY/MM/DD') AS DATA_MEDICAO,
  HORA_UTC,
  
  -- Usar NULLIF para converter 0 em NULL (dados faltantes)
  NULLIF(COALESCE(PRECIPITACAO_TOTAL, 0), 0) AS PRECIPITACAO_MM,
  NULLIF(COALESCE(PRESSAO_NIVEL_ESTACAO, 0), 0) AS PRESSAO_ATMOSFERICA_MB,
  NULLIF(COALESCE(PRESSAO_MAX_ANT, 0), 0) AS PRESSAO_ATMOSFERICA_MAX_MB,
  NULLIF(COALESCE(PRESSAO_MIN_ANT, 0), 0) AS PRESSAO_ATMOSFERICA_MIN_MB,
  NULLIF(COALESCE(RADIACAO_GLOBAL, 0), 0) AS RADIACAO_GLOBAL_KJ_M2,
  NULLIF(COALESCE(TEMP_AR_BULBO_SECO, 0), 0) AS TEMPERATURA_AR_C,
  NULLIF(COALESCE(TEMP_PONTO_ORVALHO, 0), 0) AS TEMPERATURA_PONTO_ORVALHO_C,
  NULLIF(COALESCE(TEMP_MAX_ANT, 0), 0) AS TEMPERATURA_MAXIMA_C,
  NULLIF(COALESCE(TEMP_MIN_ANT, 0), 0) AS TEMPERATURA_MINIMA_C,
  NULLIF(COALESCE(TEMP_ORVALHO_MAX_ANT, 0), 0) AS TEMPERATURA_ORVALHO_MAX_C,
  NULLIF(COALESCE(TEMP_ORVALHO_MIN_ANT, 0), 0) AS TEMPERATURA_ORVALHO_MIN_C,
  NULLIF(COALESCE(UMIDADE_MAX_ANT, 0), 0) AS UMIDADE_RELATIVA_MAX_PCT,
  NULLIF(COALESCE(UMIDADE_MIN_ANT, 0), 0) AS UMIDADE_RELATIVA_MIN_PCT,
  NULLIF(COALESCE(UMIDADE_RELATIVA, 0), 0) AS UMIDADE_RELATIVA_PCT,
  NULLIF(COALESCE(VENTO_DIRECAO, 0), 0) AS VENTO_DIRECAO_GRAUS,
  NULLIF(COALESCE(VENTO_RAJADA_MAX, 0), 0) AS VENTO_RAJADA_MAX_MS,
  NULLIF(COALESCE(VENTO_VELOCIDADE, 0), 0) AS VENTO_VELOCIDADE_MS

FROM raw_data
WHERE DATA IS NOT NULL
  AND ESTACAO IS NOT NULL
