version: 2

sources:
  - name: raw_ons
    schema: RAW_ONS
    tables:
      - name: BALANCO_ENERGIA_SUBSISTEMA_2025
      - name: BALANCO_ENERGIA_SUBSISTEMA_2024
      - name: BALANCO_ENERGIA_SUBSISTEMA_2023
      - name: DISPONIBILIDADE_USINA_GERAL
      - name: EAR_DIARIO_SUBSISTEMA_2025
      - name: EAR_DIARIO_SUBSISTEMA_2024
      - name: EAR_DIARIO_SUBSISTEMA_2023
      - name: ENA_DIARIO_SUBSISTEMA_2025
      - name: ENA_DIARIO_SUBSISTEMA_2024
      - name: ENA_DIARIO_SUBSISTEMA_2023
      - name: INMET_PROCESSED_DATA
      - name: INMET_PROCESSED_DATA_2025
      - name: INMET_PROCESSED_DATA_2024
      - name: INMET_PROCESSED_DATA_2023

      # GERACAO_TERMICA_DESPACHO - 2023 (12 meses)
      - name: GERACAO_TERMICA_DESPACHO_2023_01
      - name: GERACAO_TERMICA_DESPACHO_2023_02
      - name: GERACAO_TERMICA_DESPACHO_2023_03
      - name: GERACAO_TERMICA_DESPACHO_2023_04
      - name: GERACAO_TERMICA_DESPACHO_2023_05
      - name: GERACAO_TERMICA_DESPACHO_2023_06
      - name: GERACAO_TERMICA_DESPACHO_2023_07
      - name: GERACAO_TERMICA_DESPACHO_2023_08
      - name: GERACAO_TERMICA_DESPACHO_2023_09
      - name: GERACAO_TERMICA_DESPACHO_2023_10
      - name: GERACAO_TERMICA_DESPACHO_2023_11
      - name: GERACAO_TERMICA_DESPACHO_2023_12

      # Tabelas de 2024
      - name: GERACAO_TERMICA_DESPACHO_2024_01
      - name: GERACAO_TERMICA_DESPACHO_2024_02
      - name: GERACAO_TERMICA_DESPACHO_2024_03
      - name: GERACAO_TERMICA_DESPACHO_2024_04
      - name: GERACAO_TERMICA_DESPACHO_2024_05
      - name: GERACAO_TERMICA_DESPACHO_2024_06
      - name: GERACAO_TERMICA_DESPACHO_2024_07
      - name: GERACAO_TERMICA_DESPACHO_2024_08
      - name: GERACAO_TERMICA_DESPACHO_2024_09
      - name: GERACAO_TERMICA_DESPACHO_2024_10
      - name: GERACAO_TERMICA_DESPACHO_2024_11
      - name: GERACAO_TERMICA_DESPACHO_2024_12
      
      # Tabelas de 2025
      - name: GERACAO_TERMICA_DESPACHO_2025_01
      - name: GERACAO_TERMICA_DESPACHO_2025_02
      - name: GERACAO_TERMICA_DESPACHO_2025_03
      - name: GERACAO_TERMICA_DESPACHO_2025_04
      - name: GERACAO_TERMICA_DESPACHO_2025_05
      - name: GERACAO_TERMICA_DESPACHO_2025_06
      - name: GERACAO_TERMICA_DESPACHO_2025_07
      - name: GERACAO_TERMICA_DESPACHO_2025_08
      - name: GERACAO_TERMICA_DESPACHO_2025_09

       # FATOR_CAPACIDADE - 2023 (12 meses)
      - name: FATOR_CAPACIDADE_2023_01
      - name: FATOR_CAPACIDADE_2023_02
      - name: FATOR_CAPACIDADE_2023_03
      - name: FATOR_CAPACIDADE_2023_04
      - name: FATOR_CAPACIDADE_2023_05
      - name: FATOR_CAPACIDADE_2023_06
      - name: FATOR_CAPACIDADE_2023_07
      - name: FATOR_CAPACIDADE_2023_08
      - name: FATOR_CAPACIDADE_2023_09
      - name: FATOR_CAPACIDADE_2023_10
      - name: FATOR_CAPACIDADE_2023_11
      - name: FATOR_CAPACIDADE_2023_12
      
      # FATOR_CAPACIDADE - 2024 (12 meses)
      - name: FATOR_CAPACIDADE_2024_01
      - name: FATOR_CAPACIDADE_2024_02
      - name: FATOR_CAPACIDADE_2024_03
      - name: FATOR_CAPACIDADE_2024_04
      - name: FATOR_CAPACIDADE_2024_05
      - name: FATOR_CAPACIDADE_2024_06
      - name: FATOR_CAPACIDADE_2024_07
      - name: FATOR_CAPACIDADE_2024_08
      - name: FATOR_CAPACIDADE_2024_09
      - name: FATOR_CAPACIDADE_2024_10
      - name: FATOR_CAPACIDADE_2024_11
      - name: FATOR_CAPACIDADE_2024_12
      
      # FATOR_CAPACIDADE - 2025 (9 meses)
      - name: FATOR_CAPACIDADE_2025_01
      - name: FATOR_CAPACIDADE_2025_02
      - name: FATOR_CAPACIDADE_2025_03
      - name: FATOR_CAPACIDADE_2025_04
      - name: FATOR_CAPACIDADE_2025_05
      - name: FATOR_CAPACIDADE_2025_06
      - name: FATOR_CAPACIDADE_2025_07
      - name: FATOR_CAPACIDADE_2025_08
      - name: FATOR_CAPACIDADE_2025_09

      # RESTRICAO_COFF_FOTOVOLTAICA - 2024 (04 a 12)
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_04
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_05
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_06
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_07
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_08
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_09
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_10
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_11
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2024_12
      
      # RESTRICAO_COFF_FOTOVOLTAICA - 2025 (01 a 09)
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_01
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_02
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_03
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_04
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_05
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_06
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_07
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_08
      - name: RESTRICAO_COFF_FOTOVOLTAICA_2025_09